### ISSUE TITLE
Sha3 issue

### ISSUE THREAD

**Issue by PatrickAlphaC** [truffle-box/react-box#125]
When I run:
```
npm install -g truffle
truffle unbox react
```

I get the following issue:
```
2 warnings and 1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/patrick/code/bad/client/node_modules/sha3
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/patrick/.npm/_logs/2020-08-01T21_09_14_854Z-debug.log

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at Object.installBoxDependencies (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/unbox.js:104:1)
    at Object.setUpBox (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/lib/utils/index.js:66:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:110:1
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/truffle/build/webpack:/packages/box/dist/box.js:5:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.1.37 (core: 5.1.37)
Node v14.5.0
```

I have tried this many times. I have found [this issue](https://github.com/nodejs/node-gyp/issues/1694) which encapsulates all the attempts I've made to fix this. 

```
OS: MacOS Catalina 10.15.6 
nodejs: v14.5.0
Truffle v5.1.37
```

**Comment by CruzMolina** [comment]
Hey @PatrickAlphaC, thanks for reporting! This should now be fixed 🤞 .

**Comment by PatrickAlphaC** [comment]
It worked :D :D :D :D :D
