### ISSUE TITLE
npm start ends up errors

### ISSUE THREAD

**Issue by mtskf** [truffle-box/react-box#173]
Here are the errors seen on Chrome devtool.
I haven't edited any code. Also, I've tried with Node 14.17.5, 15.14.0, 16.15.0, 17.9.0, and all failed with the same error. I'd appreciate if you could help!

```
react-dom.development.js:22738 Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at EthProvider.jsx:49:1
    at Array.forEach (<anonymous>)
    at EthProvider.jsx:49:1
    at commitHookEffectListMount (react-dom.development.js:23049:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24816:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24781:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24768:1)
    at commitPassiveMountEffects (react-dom.development.js:24756:1)
    at flushPassiveEffectsImpl (react-dom.development.js:26990:1)
    at flushPassiveEffects (react-dom.development.js:26935:1)
    at react-dom.development.js:26725:1
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at performWorkUntilDeadline (scheduler.development.js:533:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
    at onGlobalMessage (setImmediate.js:109:1)
(anonymous) @ EthProvider.jsx:49
(anonymous) @ EthProvider.jsx:49
commitHookEffectListMount @ react-dom.development.js:23049
commitPassiveMountOnFiber @ react-dom.development.js:24816
commitPassiveMountEffects_complete @ react-dom.development.js:24781
commitPassiveMountEffects_begin @ react-dom.development.js:24768
commitPassiveMountEffects @ react-dom.development.js:24756
flushPassiveEffectsImpl @ react-dom.development.js:26990
flushPassiveEffects @ react-dom.development.js:26935
(anonymous) @ react-dom.development.js:26725
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
performWorkUntilDeadline @ scheduler.development.js:538
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27491
ensureRootIsScheduled @ react-dom.development.js:25639
scheduleUpdateOnFiber @ react-dom.development.js:25428
updateContainer @ react-dom.development.js:28804
push../node_modules/react-dom/cjs/react-dom.development.js.ReactDOMHydrationRoot.render.ReactDOMRoot.render @ react-dom.development.js:29216
(anonymous) @ index.js:7
./src/index.js @ index.js:9
__webpack_require__ @ bootstrap:851
fn @ bootstrap:150
1 @ index.js:9
__webpack_require__ @ bootstrap:851
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
```

**Comment by mtskf** [comment]
Simply MetaMask was turned off... 🫣

**Comment by lijie-lee** [comment]
Hey there. Found this issue is already closed, but I met this error recently with the content of pachage.json
```json
...
"dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "^4.0.3",
    "web3": "^1.7.5"
  }
...
```

Would you mind share some tips for solving this problem? Thanks.
