### ISSUE TITLE
truffle unbox react is not working

### ISSUE THREAD

**Issue by HamzaUmer** [truffle-box/react-box#181]
Unbox failed!
RequestError: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyhost
    at ClientRequest.<anonymous> (C:\Users\mirza\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\download\node_modules\got\index.js:182:1)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.onError (C:\Users\mirza\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\tunnel-agent\index.js:179:1)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:193:8)
    at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Truffle v5.5.28 (core: 5.5.28)
Node v16.4.0

**Comment by cliffoo** [comment]
Hey @HamzaUmer, is your machine connected / behind some proxy? Try `env | grep proxy`.

Also here's a [related issue](https://github.com/trufflesuite/truffle/issues/5108) over on the Truffle repo that may be helpful.

**Comment by rghvsomani** [comment]
Hey !! could you help me to resolve these error occurred while running this project
error 1)
showing error for 
import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
as Assert.sol file doesn't exists in tuffle module
2)error while running the program
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\DELL\Downloads\E-Certify-master\pro/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\DELL\Downloads\E-Certify-master\pro\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by cliffoo** [comment]
Closing for issue maintenance.
