### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by Meekohi** [truffle-box/react-box#22]
Fresh unbox on OSX:
```
> npm run start
Failed to compile.

Error in ./src/index.js
Module build failed: Error: Failed to load plugin babel: Cannot find module 'eslint-plugin-babel'
    at Array.forEach (native)
 @ multi main
```

**Comment by Meekohi** [comment]
```
> npm test
Determining test suites to run...2017-10-07 15:19 node[6994] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-10-07 15:19 node[6994] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
npm ERR! Test failed.  See above for more details.
```

**Comment by didil** [comment]
did you run npm install ?

**Comment by Meekohi** [comment]
Yes indeed.

**Comment by dr-orlovsky** [comment]
Same for me

**Comment by jordanglassman** [comment]
I fixed the test problem by installing watchman:  https://github.com/facebook/react-native/issues/910#issuecomment-94181845
