### ISSUE TITLE
Bug in unboxing react

### ISSUE THREAD

**Issue by chuacw** [truffle-box/react-box#25]
When following the instructions on this page: http://truffleframework.com/boxes/react and running the command: `truffle unbox react` on Truffle v4.0.0-beta.2 (core: 4.0.0-beta.2), I got the following errors.

This is an Administrator account.

Error: Command failed: npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ?  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Development\Ethereum\react\node_modules\scrypt
gyp ERR! node -v v8.8.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, scandir 'D:\Development\Ethereum\react\node_modules\fsevents\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'D:\Development\Ethereum\react\node_modules\fsevents\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\Development\\Ethereum\\react\\node_modules\\fsevents\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'D:\\Development\\Ethereum\\react\\node_modules\\fsevents\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2017-10-29T09_59_44_627Z-debug.log

    at ChildProcess.exithandler (child_process.js:272:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

**Comment by juanpasolano** [comment]
Having exact same issue
node v6.10.0
npm 5.6.0

**Comment by omkarkhair** [comment]
Ditto.

**Comment by rasommer** [comment]
Follow the installation instructions [https://github.com/nodejs/node-gyp](url)
I installed the build-essential package on my ubuntu, for example.

**Comment by Sunfcy** [comment]
同上
