### ISSUE TITLE
Is there any requirement for python2.7 on package <scrypt@6.0.3> 

### ISSUE THREAD

**Issue by Renderz** [truffle-box/react-box#40]
env: Windows 10
I have installed python3.6 successfully on my laptop.
but still error showed while npm installing.
```λ npm i
npm WARN deprecated ethereumjs-testrpc@2.2.7: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.

> scrypt@6.0.3 preinstall C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\scrypt
> node-gyp rebuild


C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\renderio\AppData\Local\Programs\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\scrypt
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN Error: EPERM: operation not permitted, scandir 'C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'C:\Users\renderio\Desktop\react-box-master\react-box-master\node_modules\fsevents\node_modules\getpass\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'C:\\Users\\renderio\\Desktop\\react-box-master\\react-box-master\\node_modules\\fsevents\\node_modules\\getpass\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'C:\\Users\\renderio\\Desktop\\react-box-master\\react-box-master\\node_modules\\fsevents\\node_modules\\getpass\\node_modules' }npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\renderio\AppData\Roaming\npm-cache\_logs\2018-01-12T07_33_32_185Z-debug.log
```

I wonder whether it requires python2.7 cause on the certain path i found the python.exe exactly. It didnt affect anything till now thought.

**Comment by Renderz** [comment]
I found that <scrypt> requires <node-gyp> as dependency, and <node-gyp> requires <windows-build-tools> as dependency on windows env which rolls up python2.7 / visual studio /c++ build tools in a package.
[](https://github.com/barrysteyn/node-scrypt)
