### ISSUE TITLE
Truffle unbox error - "doesn't exist"

### ISSUE THREAD

**Issue by mrice** [truffle-box/react-box#93]
Hi folks-

Created a new folder and have truffle 4.1.14 installed globally. Ran the command `truffle unbox react` and got this error:

```
Downloading...
Error: Truffle Box at URL https://github.com/truffle-box/react-box doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (/usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

When I navigate to the Github url mentioned in the error, everything shows up fine for me....

**Comment by MagRelo** [comment]
Upgrading to truffle v5 fixed this for me (I was on v4.1.4)
